// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTURUJzMAYiyDO60jCBz5zb70jytshH2c',
    appId: '1:199624523333:web:6067c3b8b68937ff1fad2c',
    messagingSenderId: '199624523333',
    projectId: 'madad-4b373',
    authDomain: 'madad-4b373.firebaseapp.com',
    databaseURL: 'https://madad-4b373-default-rtdb.firebaseio.com',
    storageBucket: 'madad-4b373.firebasestorage.app',
    measurementId: 'G-HB6LSNT8PJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGKIWqTr7RpFozF6Gqmyx37O1HRxRXwyU',
    appId: '1:199624523333:ios:5e279b95d2fa29a41fad2c',
    messagingSenderId: '199624523333',
    projectId: 'madad-4b373',
    databaseURL: 'https://madad-4b373-default-rtdb.firebaseio.com',
    storageBucket: 'madad-4b373.firebasestorage.app',
    androidClientId: '199624523333-fse2e6h2jmkj0mp4kunmliu08r4f78ak.apps.googleusercontent.com',
    iosClientId: '199624523333-6ku1llvd9nom0a76q72sie3849ovckds.apps.googleusercontent.com',
    iosBundleId: 'com.maven.madaduser.User',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr3J9I6f7YSC0x8TvtNcl48O87mb8CZ0Y',
    appId: '1:199624523333:android:ddb34e4b29c249821fad2c',
    messagingSenderId: '199624523333',
    projectId: 'madad-4b373',
    databaseURL: 'https://madad-4b373-default-rtdb.firebaseio.com',
    storageBucket: 'madad-4b373.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTURUJzMAYiyDO60jCBz5zb70jytshH2c',
    appId: '1:199624523333:web:fbaac1fbd5f8c3a31fad2c',
    messagingSenderId: '199624523333',
    projectId: 'madad-4b373',
    authDomain: 'madad-4b373.firebaseapp.com',
    databaseURL: 'https://madad-4b373-default-rtdb.firebaseio.com',
    storageBucket: 'madad-4b373.firebasestorage.app',
    measurementId: 'G-2ZXBJBJ7F8',
  );

}